version: '3.8'

services:
  web:
    image: image:latest
    container_name: portfolio-web
    ports:
      - "80:80"
    volumes:
      - ./html/var/www/html
    networks:
      - frontend

networks:
  frontend:
